// AUTO-GENERATED by scripts/scrape-powderhounds.ts — do not edit manually
// Last scraped: 2026-02-18T06:37:53.916Z

export interface PowderhoundsData {
  rating: string | null;
  description: string;
  pros: string[];
  cons: string[];
  proOrCon: string[];
  terrainStats: {
    runs: string | null;
    longestRun: string | null;
    season: string | null;
    beginner: string | null;
    intermediate: string | null;
    advanced: string | null;
    lifts: string | null;
    vertical: string | null;
    snowfall: string | null;
  };
  sourceUrl: string;
  scrapedAt: string;
}

// Key = resort id from resorts.ts
export const powderhoundsData: Record<string, PowderhoundsData> = {
  "grandvalira": {
    "rating": "3.5",
    "description": "Grandvalira ski resort is the largest in Andorra & the entire Pyrenees. If large, interconnected ski resorts with multiple villages but without the crowds are your thing, Grandvalira may be for you.\n\nOnly a few minutes from the capital city, Grandvalira provides a unique ski holiday experience. Ski a world-class resort in one of the smallest countries in the world!",
    "pros": [
      "Vast network of lifts & ski trails.",
      "All ski terrain over 1,700m elevation.",
      "Quality on-piste trails for beginner & intermediate skiers & snowboarders.",
      "Lift pass valid in the fun Ordino Arcalis ski resort.",
      "Public transport access by train & bus is fantastic.",
      "A multitude of hotel & apartment options in valley or mountain village locations, for every budget, all lift connected to the ski resort.",
      "Ski-in ski-out accommodation available."
    ],
    "cons": [
      "Several confusing lift/piste connections for the uninitiated.",
      "Boom/bust snow cycle in the Pyrenees with increasing winter temperatures impacting snow quantity & quality at lower elevations.",
      "For a resort so big, there is limited freeride powder & advanced terrain.",
      "Public transport from French or Spanish airports to Andorra is remarkably limited & difficult to manage."
    ],
    "proOrCon": [
      "An international clientele that may, or may not, appeal to one’s sensibilities, particularly in the higher-priced accommodation!",
      "Resort villages seem quite soulless, lacking any sense of integrated ‘community’, but maybe that’s what visitors here are seeking.",
      "Access to Europe’s best value vices in the booze, cigarette & sweet departments; plus cheap fuel - there are more petrol stations here per capita then just about anywhere else in Europe (the possible exception is duty-free Livigno!)."
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": "6km",
      "season": "mber–late",
      "beginner": "46%",
      "intermediate": "36%",
      "advanced": "18%",
      "lifts": "70",
      "vertical": "1,710m - 2,640m (930m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Andorra/Grandvalira.aspx",
    "scrapedAt": "2026-02-18T06:15:26.351Z"
  },
  "kitzbuhel": {
    "rating": "4",
    "description": "Kitzbuhel is the epitome of the perfect Austrian ski resort. Ski lifts extending from the centre of a real town, huge terrain in classic Austrian countryside plus an après scene that rivals the best in the world, makes Kitzbuhel an unforgettable skiing and snowboarding experience.\n\nJust like many of the Austrian mega resorts, Kitzbϋhel ski resort (a.k.a. KitzSki - which includes all the interconnected lifts & pistes valid on the lift pass) is lift, piste and ticket interlinked with Kirchberg to the west and extends south through Jochberg into the Salzburg state at Hollersbach-im-Pinzgau & Mittersill. With so many access points, there is simply no excuse not to ski one of the world's best ski resorts.\n\nThe Powderhounds' forays here included lovely powder on busy bluebird days, plus several stormy, deep powder days. We had an awesome time on each visit, but only skied a small portion of th entire Kitzski, such is the resort’s immense scale.",
    "pros": [
      "Huge & diverse lift interlinked ski area perfect for a week-long ski holiday.",
      "Ultra-modern & efficient lift system.",
      "Excellent range of piste trails for all levels, including loads of interesting valley runs & marked ski routes.",
      "Fantastic variety of off-piste freeride terrain.",
      "Freeride terrain & ski areas toward Pass Thurn are surprisingly uncrowded.",
      "Superb quality & quantity of mountain huts with bars, restaurants & accommodation.",
      "Some of the world’s best après ski, particularly in the mountain huttes as one descends toward the valleys.",
      "Wide range of accommodation in numerous villages including ski-in ski-out lodgings.",
      "Good value lift pass price for all the terrain & wonderful facilities provided.",
      "Easy public transport access by train & bus plus ample free car parking for day trippers right near lifts (but away from Kitzbuhel!).",
      "Free buses interlinked the villages."
    ],
    "cons": [
      "Busy on-piste & at lift queues in the Kitzbuhel sector of the resort.",
      "In a poor winter it can be ‘altitude challenged’ on the lower half of the mountain - all terrain is below 2,000m elevation.",
      "Lift lines are absolutely unforgiving & require a level of attitude to match & move forward (whilst still maintaining your polite visage!).",
      "Short(ish) skiable verticals in the sector around Resterhöhe.",
      "Accommodation in Kitzbühel village itself can be hard to get & expensive."
    ],
    "proOrCon": [
      "Too much choice.",
      "Low altitude villages may not have snow at either end of the season (but the slopes will!).",
      "Kitzbuhel doesn’t lack terrain in general, but it has a relatively limited high alpine area above the tree line compared to other ski resorts. If looking for high alpine terrain, head elsewhere.",
      "Plenty of well-priced accommodations available in the pass Thurn/Hollersbach sector of the Kitzski resort, but you are not in Kitzbühel anymore!",
      "Rightfully popular but not uncomfortably so, if you don’t like skiing mega resorts perhaps look elsewhere."
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": "58",
      "vertical": "800m - 2,004m (1,204m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Austria/Kitzbuhel.aspx",
    "scrapedAt": "2026-02-18T06:15:40.292Z"
  },
  "ischgl": {
    "rating": "4",
    "description": "Ischgl ski resort in the Silvretta mountains of western Tyrol is one of Austria's most popular snow holiday destinations. The resort has a deserved reputation for excellent skiing & snowboarding plus a serious party scene.\n\nSituated on the frontier with Switzerland, Ischgl is interlinked with Samnaun ski resort to create a huge & diverse ski area of over 239km of trails & 46 modern ski lifts. Ischgl will delight Powderhounds of all abilities with the range, size & quality of the snow, lifts & terrain, but may disappoint with its volume of humanity! Start early here or get lost in the pack….\n\nIschgl is renowned for its fun après sessions in the mountain huts & the village. Be prepared for music, drink & dancing from lunchtime & well into the night, most nights.",
    "pros": [
      "Huge ski area spanning two countries (linked to Samnaun Switzerland);",
      "Consistent and quality snow.",
      "Long season from November to May.",
      "Variety of on & off-piste terrain to suit all abilities & sense of adventure.",
      "Expansive easy access backcountry terrain.",
      "Super-modern & efficient lift infrastructure.",
      "Good value lift pass.",
      "Silvretta lift pass (valid in the smaller, but delightful, Galtuer, Kappl & See ski resorts) provides welcome relief from the crowds.",
      "Superb access to ski lifts & multiple return ski trails in the village."
    ],
    "cons": [
      "Extremely busy during peak periods.",
      "Few challenges on-piste for advanced skiers & riders.",
      "Inbounds off-piste terrain gets tracked out quickly on a powder day.",
      "Accommodation can be expensive and hard to get, so the fall back is inevitably Landeck Zams if leaving it to the last minute."
    ],
    "proOrCon": [
      "Majority of Ischgl’s pistes are north-facing so are less sun-drenched than in Samnaun.",
      "Ischgl village is a modern resort style version of a traditional Austrian village.",
      "A massive après ski scene from lunchtime onward - love it or loath it - you choose!"
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": "Nov–earl",
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": "46",
      "vertical": "1,371m - 2,872m (1,501m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Austria/Ischgl.aspx",
    "scrapedAt": "2026-02-18T06:15:53.783Z"
  },
  "chamonix": {
    "rating": "3.5",
    "description": "Legendary Chamonix in France should be on any ski or snowboard bucket list. Chamonix has an allure for the hard core & adventurous, with world renowned off-piste skiing and freeriding. Some of the lines are so challenging that one may need to wear a nappy (or diaper, incontinence pad) to avoid embarrassment!\n\nThe area is dominated by the highest mountain in Western Europe, 4,810m Mont Blanc. It serves as a playground for extreme sports enthusiasts and the ooh aah brigade. Between ice climbing, paragliding and extreme skiing, it’s not surprising that Chamonix has been described as the \"the death-sport capital of the world\"! One must only view the engineering for the amazing Aiguille du Midi cable cars in order to comprehend that parts of Chamonix are on the edge.\n\nIf you’re not an expert ski mountaineer, Chamonix also has a 'softer' side for those who just want a relaxed European ski holiday. The 11 Chamonix ski areas have more than 170km of piste on which to cruise, including several excellent learn-to-ski areas. The 4 main ski resorts are Grands Montets, Balme-Tour-Vallorcine, Brevent-Flegere & Les Houches. There are plenty of restaurants & bars to enjoy the famous food & wine at each resort.",
    "pros": [
      "Glorious location & surrounding mountains.",
      "Good range of piste trails for all abilities on all aspects.",
      "Superb off-piste & freeride terrain including glaciers & tree skiing.",
      "Generally, quite good value (for a large French ski area!).",
      "Excellent après ski & restaurants in a wonderfully vibrant town.",
      "Swift access by road, bus or train from the airport at Geneva."
    ],
    "cons": [
      "Ski areas are not lift interconnected.",
      "Limited ski-in ski-out accommodation.",
      "Powder days have got alot of 'local' competition for fresh lines.",
      "Transport between the different ski areas can be extremely busy during peak times.",
      "Lift infrastructure is getting quite dated in some sectors.",
      "Lift pass options are needlessly complex."
    ],
    "proOrCon": [
      "Chamonix & all the surrounding villages are lively, real towns not just resorts.",
      "World’s most extreme ski lift & terrain.",
      "Valley elevation is quite low & often has no snow.",
      "Ski areas spread across a wide area (but are connected by train & free bus).",
      "Ikon Pass & Mountain Collective Pass are now valid in the region, which could be good for some ......... & potentially bad for everyone else!"
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": "mber–earl",
      "beginner": "50%",
      "intermediate": "35%",
      "advanced": "15%",
      "lifts": "61",
      "vertical": "1,000m - 3,840m (2,840m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/France/Chamonix.aspx",
    "scrapedAt": "2026-02-18T06:17:09.473Z"
  },
  "megeve": {
    "rating": "4",
    "description": "Megeve ski resort is centred on the charming & refined village of the same name in France's renowned Haute Savoie. Megève is known for its protection of history, tradition & authenticity, characteristics which in many French ski resorts have been laid to waste. The lovely, lively village is connected to St Gervais les Bains, via a huge network of lifts & mainly beginner-intermediate ski trails with a quadricep-melting local skiable vertical of over 1,450m. Part of the vast Evasion Mont Blanc ski pass region, and close to the Chamonix valley & Les Contamines, there is no shortage of mountain splendour and ski adventure.\n\nMegeve is for families, couples & groups that are looking for long, easy slopes, comfortable accommodation, diverse non-ski activities and a fabulous food experience. Hardcore powder hounds should venture here for a look and taste some fun skiing when the snow level is below 1,000m altitude.",
    "pros": [
      "Authentic French Alps village & ski resort.",
      "Long vertical of over 1,500m, with the longest actual skiable vertical around 1,050m.",
      "Enormous network of lifts & ski trails.",
      "Quality on-piste trails for, novice, beginner & intermediate skiers & snowboarders.",
      "Excellent value lift pass (Evasion Mont Blanc) that covers a vast amount of terrain, including neighbouring ski areas like Les Contamines-Hauteluce.",
      "Public transport access by a combination of train & bus is good.",
      "Village bus transport is excellent."
    ],
    "cons": [
      "Low elevation villages and some ski terrain may not have natural snow (or any snow) for much of winter.",
      "Lift system on the Megève side of the broader resort is generally quite dated and includes numerous surface tows.",
      "Can get quite busy in and around Megeve, including the main road through the town.",
      "Limited advanced on-piste & quality off-piste terrain (unless it snows quite low!)."
    ],
    "proOrCon": [
      "Lift & piste connections to/from the village are not the best.",
      "Will often require a lift download (or two or three!) to get back to the village.",
      "Accommodation can be relatively expensive & hard to get at short notice (but good alternatives are nearby that interlink with Megève.",
      "Close to Chamonix & Mont Blanc."
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": "7km",
      "season": "mber–mid",
      "beginner": "48%",
      "intermediate": "39%",
      "advanced": "13%",
      "lifts": "54",
      "vertical": "Megeve-St Gervais 900m - 2,353m (1,453m) Evasion Mont Blanc 900m - 2,437m (1,537m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/France/Megeve.aspx",
    "scrapedAt": "2026-02-18T06:18:11.409Z"
  },
  "cortina": {
    "rating": "3.5",
    "description": "The beating heart of the Dolomites, the ski resort of Cortina d’Ampezzo Italy has long been one the most sophisticated centres for style and the outdoors in Italy.  The skiing is diverse. Cortina Italy is as world renowned for its perfectly groomed pistes for all levels, as for its superb tree skiing and multitudes of expert only couloirs.\n\nThe mountains surrounding Cortina are amongst the Dolomites highest and most dramatic. They include classics such as Tofana, Sorapis and Cristallo plus that well-known formation, the Cinque Torri. In town you will be just as home wearing ski boots & gore-tex as you would high heels and furs. Part of the largest interlinked ski area in the world, the Dolomiti Superski, Cortina should be visited by every Powderhound as least once in your life.",
    "pros": [
      "Stunning views and landscapes.",
      "High elevation lifted ski terrain, with most above 1,600m.",
      "Dolomites second longest skiable vertical, a staggering 1,611m from Bus Tofana all the way down to below Cortina.",
      "Superb rifugi offer panoramas & mountain dining experiences unequalled in the world.",
      "Interesting variety of on-piste trails for all levels.",
      "One of the world’s best intermediate ski trails - Lagazuoi -> Hidden Valley -> Armentarola (scenery, length, perfect piste, frozen waterfalls, history, horse drawn skiing, rifugi).",
      "Italy’s best range & number of black (advanced) piste trails.",
      "When the snow is deep, challenging freeride terrain abounds like nowhere else.",
      "Some of Europe’s most challenging couloirs (when the snow is deep enough!).",
      "Excellent après ski and nightlife.",
      "Great restaurant food and drink."
    ],
    "cons": [
      "Not a great recent snow record, is often boom & bust (but the snowmaking covers 95% of the pistes).",
      "Generally aging lift infrastructure (that is now slowly being upgraded in some parts).",
      "Relatively expensive lift pass.",
      "Several separate ski areas, not well lift linked tot the town.",
      "Limited ski in / ski out accommodation."
    ],
    "proOrCon": [
      "Three major ski areas that are not lift connected to each other.",
      "Often sunny (i.e. it is not snowing!).",
      "Ikon Pass is conditionally valid - good for some, maybe not so good for those that don't have one"
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": "7km",
      "season": "Nov–earl",
      "beginner": "33%",
      "intermediate": "45%",
      "advanced": "16%",
      "lifts": "35",
      "vertical": "1,220m - 2,830m (1,610m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/Cortina.aspx",
    "scrapedAt": "2026-02-18T06:18:22.517Z"
  },
  "kronplatz": {
    "rating": "4",
    "description": "Kronplatz Ski Resort (a.k.a. Plan de Corones) in the northern Dolomites has a whopping 1,325 vertical metres of ski and snowboard terrain to suit everyone - tick. Kronplatz Italy is located on the outskirts of the delightful Brunico (Bruneck) and has its own railway station (Perca/Percha) directly at a gondola base - tick. Kronplatz has incredible snow-making, lift infrastructure and perfect piste trails - tick.\n\nThe only thing that could make it better is being part of the Dolomiti Superski area - tick. Add direct train links to other Dolomiti ski areas like 3 Peaks Dolomites (a.k.a. Drei Zinnen) plus Sillian in Austria & an easy bus link to Alta Badia - tick. Certainly ticks a few boxes!",
    "pros": [
      "World's best for access to a ski resort by train (equal best with Folgarida-Marilleva & Switzerland’s Aletsch Arena).",
      "Excellent lift system – maybe world’s best & if not certainly world’s most comfortable!",
      "Superb beginner and intermediate on-piste terrain.",
      "Several excellent long advanced trails.",
      "World's best snow-making capabilities.",
      "Guaranteed quality snow on piste.",
      "Great city to explore nearby (Brunico).",
      "Loads of ski schools and family fun parks and trails.",
      "Numerous incredible accommodation options available, including several ski-in, ski-out."
    ],
    "cons": [
      "Can get remarkably busy during peak holiday periods.",
      "Not much for expert skiers & snowboarders, but the long runs will challenge everyone’s endurance!",
      "Snow quality on the lower pistes can be questionable.",
      "Limited off-piste.",
      "Relatively expensive lift pass local accommodation."
    ],
    "proOrCon": [
      "Is wonderful for on-piste skiers & snowboarders i.e. Groomerhounds.",
      "Constant removal of skis required due to all the gondolas!",
      "No single resort village but loads of options as a result.",
      "Ikon Pass is now valid in the resort for up to a week."
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": "Nov–mid",
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": "33",
      "vertical": "950m - 2,275m (1,325m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/Kronplatz.aspx",
    "scrapedAt": "2026-02-18T06:18:32.206Z"
  },
  "alta-badia": {
    "rating": "3.5",
    "description": "Nestled between the Sella massif and the looming Sassongher, Alta Badia ski resort provides the traditional Italian alpine experience in an exquisite setting. Offering classic Dolomites on-piste terrain and a veritable moving feast of bars, mountain huts and restaurants, Alta Badia is far more than just a ski or snowboard experience.\n\nAlta Badia is fantastic thanks to fast and comfortable ski lift connections, sensational snow making, wide and well-groomed slopes, plus traditional Ladin, Mediterranean and South Tyrolean eating (and drinking) experiences that are hard to match. Beginners, intermediates & gourmands alike will enjoy all this region has to offer.",
    "pros": [
      "Superb piste trails for beginners, intermediates & families.",
      "Modern interconnected lift system.",
      "Glorious scenery.",
      "Huge number of high-quality mountain huts & rifugi.",
      "Central access to all major Dolomites ski resorts.",
      "The best mountain bars & restaurants in the Dolomites.",
      "Exceptional snow making system covering all piste trails."
    ],
    "cons": [
      "Limited advanced or challenging terrain.",
      "Some lifts & piste trails overcrowded.",
      "Some villages (La Villa) in near total shade for much of winter.",
      "Natural snowfalls are less reliable than in the past."
    ],
    "proOrCon": [
      "Part of the Sella Ronda & Great War ski circuits.",
      "Après ski is abundant, but aside from two notable exceptions, the nightlife tends to be a little quieter & more refined than in other Dolomites’ ski resorts.",
      "Ikon Pass is now valid in the resort for up to a week."
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": "Nov–earl",
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": "53",
      "vertical": "1,324m - 2,550m (1,246m) Dolomiti Superski 950m - 3,269m (2,319m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/Alta-Badia.aspx",
    "scrapedAt": "2026-02-18T06:18:40.816Z"
  },
  "val-gardena": {
    "rating": "3.5",
    "description": "Val Gardena is in a valley dominated by the classic Dolomites peak of Sassolungo & the huge Sella massif - a view skiers first enjoyed here as early as 1895. Since then Val Gardena has grown to become one of the most popular resorts in the Dolomiti, especially for families & intermediate skiers & snowboarders.\n\nWith more than 175km of runs connected by an incredible array of lifts, Val Gardena also gives snowboarders & skiers direct access to the Sella Ronda network plus the huge Dolomiti SuperSki area.\n\nVal Gardena has been honoured in the past as the Numero Uno Italian ski resort, based on the ski resort size, standard & facilities. Locals speak German, Italian & their regional dialect “Ladin”. Their approach combines the best of these cultures to bring you a passion for life, food, music, fun & perfection!",
    "pros": [
      "Biggest ski resort in the Dolomites.",
      "Best range of intermediate piste trails in the Dolomiti Superski area (& perhaps Italy).",
      "High quality lift system.",
      "The most amazing ‘fun slope’ in the world.",
      "Great value lift pass comparative to the number of lifts & terrain.",
      "Integral part of the Sella Ronda ski circuit & Dolomiti Superski area.",
      "Numerous lively après ski options.",
      "Ski-in ski-out accommodation available on mountain & in villages.",
      "Superb mountain huts & rifugi.",
      "Located in one of the most spectacular mountain areas of the world."
    ],
    "cons": [
      "A massive resort that does get busy.",
      "Limited off-piste freeride terrain.",
      "Relatively limited advanced terrain (but with a few very good black runs on the piste).",
      "Accommodation can be hard to get & may be relatively expensive.",
      "Ski area is not quite fully integrated by lifts & pistes - effectively four separate ski areas (but to be fair, apart from Alpe di Siusi, they are only separated by a short walk)."
    ],
    "proOrCon": [
      "Three separate major villages, plus many smaller ones.",
      "Piste trails spread across a huge distance.",
      "Italy’s most popular ski area.",
      "Ikon Pass is now valid in the resort for up to a week."
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": "Nov–earl",
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": "81",
      "vertical": "1,230m - 2,518m (1,288m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/Val-Gardena.aspx",
    "scrapedAt": "2026-02-18T06:19:17.598Z"
  },
  "val-di-fassa": {
    "rating": "4",
    "description": "Val di Fassa ski resort in the Dolomites is a classic Italian 8-part degustation. The entree is on Catinaccio, mains are centred on Col Rodella, the Belvedere or Ciampac & Buffaure, with Sass Pordoi & Fedaia on the flanks of Marmolada the dessert selection. The collection of different ski areas total a surprising small 75km of piste trails but includes hugely diverse terrain ranging from perfect beginner areas to serious freeride routes plus everything in between.\n\nVal di Fassa Italy has numerous classic Dolomites villages (Canazei, Campitello, Pozza di Fassa, Vigo di Fassa) & mountain rifugi, creating a superb ski destination. With lift & piste links to neighbouring resorts as well, the big questions of where to stay & where to ski each day are wonderful problems to have!",
    "pros": [
      "Fabulous family friendly snow holiday destination.",
      "Glorious Dolomites surrounds.",
      "Excellent beginner, intermediate & advanced piste trails.",
      "Some quiet, seemingly isolated 'skiing gems' in amongst the hoi polloi.",
      "Modern, comfortable ski lifts.",
      "Spectacular off-piste freeride routes from Saas Pordoi & Marmolada.",
      "Seamless lift & piste connection with Arabba & Val Gardena.",
      "World-class snow-making (regardless of Mother Nature’s fickleness).",
      "Typically great Dolomites' mountain restaurants, bars & rifugi.",
      "’Ski-in ski-out’ accommodation available on the mountain & sensational agri-turismo in the countryside."
    ],
    "cons": [
      "Ski area spread across a wide valley & not fully lift interlinked.",
      "Bus journeys link different ski areas (aaargh!) & most buses cost a small additional fee (double aaargh).",
      "Some pistes & lifts on the Col Rodella & Belvedere get busy with Sella Ronda ‘traffic’ (beep beep)."
    ],
    "proOrCon": [
      "Not known as a powder ski destination but has more marked freeride options than any other Dolomites ski areas.",
      "No single main village or centre.",
      "Limited high-end (5-star) accommodation (does anyone really care, I mean really?).",
      "Close to historic, yet cosmopolitan Bolzano & its transport links to the rest of Europe.",
      "IKON Pass now valid in the resort - good or bad, you be the judge!"
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": "Nov–earl",
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": "47",
      "vertical": "1,200m - 2,950m (1,750m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/Val-di-Fassa.aspx",
    "scrapedAt": "2026-02-18T06:19:23.817Z"
  },
  "cervino": {
    "rating": "4",
    "description": "At the foot of Monte Cervino (a.k.a. the Matterhorn) on the Italian side of the border across from Zermatt is the Cervinia ski resort. Beautifully situated in a broad glacier capped bowl, Cervinia has awesome skiing & dining experiences at a bargain basement price in the Valle d'Aosta Italy.\n\nBefore Cervinia was developed as a ski resort, the village was a base for mountaineering types & it was known as Breuil. It’s officially now known as Breuil-Cervinia, but most people just refer to it as Cervinia. The resort includes Valtournenche & is lift, trail & pass interlinked with Zermatt in Switzerland to form one of the largest international ski resorts in the world (behind the likes of the monstrous Portes du Soleil).\n\nSignificantly less expensive than neighbouring Zermatt, Cervinia has awesome Italian food & drink plus ideal terrain for beginner, intermediate & freeride powder seeking skiers & snowboarders.",
    "pros": [
      "Stunning views and landscapes.",
      "High altitude guarantees quality and reliable snow.",
      "Excellent, long distance piste trails for beginners and intermediates on a skiable vertical of over 1,400m on the Italian side.",
      "Ski lift infrastructure is being progressively modernised (gotta 'keep up with the joneses' over the border!).",
      "World's most spectacular learn to ski area.",
      "Long season, including summer skiing.",
      "Superb on-mountain restaurants & après ski.",
      "Great freeride terrain including tree skiing for advanced riders.",
      "Excellent value for money.",
      "Linked with Zermatt Switzerland (and a lot cheaper too).",
      "Quiet during the week.",
      "Lots of ‘ski-in’ lodging options."
    ],
    "cons": [
      "The Cervinia sector is very exposed during blizzards and upper mountain lifts often close during high winds.",
      "No piste trails for advanced riders.",
      "The drive up to Cervinia village (2,050m altitude) can be challenging during stormy weather or icy conditions, & when weekend traffic is coming the other way!"
    ],
    "proOrCon": [
      "Off-piste skiing for more advanced riders requires a little bit of knowledge & effort.",
      "Much of the privately owned on-mountain apartment accommodation is old and dated, but also very cheap (renter beware!).",
      "High-end accommodation is more readily available in the last few years at Breuil Cervinia, but head to Zermatt if luxury is an important factor.",
      "Heli-skiing is available.",
      "Summer skiing is becoming increasingly limited as climate change takes hold.",
      "IKON Pass is valid in adjacent Zermatt but NOT in Cervinia!"
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": "20km",
      "season": "Oct–Earl",
      "beginner": "36%",
      "intermediate": "58%",
      "advanced": "6%",
      "lifts": "22",
      "vertical": "Cervinia - Valtournenche only 1,524m - 3,480m (1,956m) Incl. Zermatt 1,524m - 3,899m (2,475m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/Cervinia.aspx",
    "scrapedAt": "2026-02-18T06:19:36.503Z"
  },
  "courmayeur": {
    "rating": "4",
    "description": "Courmayeur ski resort in the famed Aosta valley Italy is perfectly located on the sunny side of the Monte Bianco (Mont Blanc) massif. Courmayeur is a beautiful, refined town with an adventurous, big mountain spirit.\n\nExcellent lift access from near the centre of Courmayeur provides both family-friendly & action-packed skiing & snowboarding within minutes of leaving your accommodation. The ski terrain combines 1,550m vertical descents from the main ski resort area and huge, challenging off-piste descents of over 2,150m vertical from Punta Helbronner on the flanks of Monte Bianco.",
    "pros": [
      "Set amongst the most breathtaking mountains in Europe.",
      "Reliable snow quality & quantity (for Italy!), particularly on the colder north-aspects.",
      "A refined, but relaxed, friendly, and adventurous town.",
      "Fantastic larch forest tree skiing on north-facing slopes.",
      "Diverse ski opportunities including Mont Blanc (Monte Bianco!).",
      "Long skiable vertical of 1,550m in the resort.",
      "Superb off-piste and backcountry routes accessible via the ski lifts.",
      "Amazing place to undertake some ski touring.",
      "Delicious food and fun après; both on & off the ski hill.",
      "Wonderful shopping; from high-end to outdoorsy."
    ],
    "cons": [
      "Minimal transitional beginner terrain.",
      "Ski resort is relatively small when compared to others nearby.",
      "Upper cable cars (& some chairlifts) in the resort are ancient & have limited capacity, leading to line-ups on powder days.",
      "Social media has played a part in skyrocketing numbers of freeriders on the Skyway Monte Bianco on powder days.",
      "Long flat exit from freeride descents into Val Veny from d'Arp."
    ],
    "proOrCon": [
      "Whilst not necessarily busy on weekends, the local skiers do have a superhuman ability to track out the best off-piste areas in the resort early on a weekend powder day - don’t sleep in!",
      "Easy to get to by motorway from both Italy and France.",
      "The glaciers on the Italian side of Mont Blanc/Monte Bianco are rapidly disappearing, get here sooner rather than later."
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": "Nov–mid",
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": "20",
      "vertical": "Courmayeur 1,205m - 2,755m (1,550m) Skyway Monte Bianco 1,306 - 3,466 (2,160m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/Courmayeur.aspx",
    "scrapedAt": "2026-02-18T06:20:21.021Z"
  },
  "la-thuile": {
    "rating": "3.5",
    "description": "La Thuile ski resort in Italy is a fun, low key, snow magnet near the head of the Aosta valley. Situated at the end of the road in winter, a short distance from Courmayeur, close to the border with France and surrounded by Mont Miravidi and the Rutor Glacier, La Thuile has all the mountain splendour one could ever wish for.\n\nLoads of beginner & lower intermediate piste terrain, a wonderful off-piste & freeride terrain, reliable snowfall, plus fun challenges for the more advanced & adventurous, makes La Thuile a great ski destination and Powderhounds favourite. Its international link with La Rosiere ski resort in France adds some more spice to the sauce!",
    "pros": [
      "Excellent snow quality & quantity.",
      "Glorious range of off-piste freeride terrain for beginner to advanced powder hounds.",
      "Uncrowded.",
      "Fun tree skiing.",
      "Child & family friendly terrain.",
      "Sensational value for money - lifts & accommodation.",
      "Fabulous views.",
      "Delectable mountain hut dining.",
      "Heli-skiing & backcountry access is great.",
      "International border crossing, plus lift, piste & pass linked to La Rosiere!"
    ],
    "cons": [
      "Piste trails generally not challenging (with some notable exceptions!).",
      "Some long, flat traverses are not snowboard friendly.",
      "Dated base & resort facilities."
    ],
    "proOrCon": [
      "Village is in deep shade for much of winter.",
      "No high-end luxury (5-star et al) accommodation in the area (go to Courmayeur)."
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": "11 km",
      "season": "Nov–mid",
      "beginner": "27%",
      "intermediate": "46%",
      "advanced": "27%",
      "lifts": "17",
      "vertical": "La Thuile only 1,450m - 2,650m (1,200m) Espace San Bernardo 1,170m - 2,800m (1,630m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/La-Thuile.aspx",
    "scrapedAt": "2026-02-18T06:21:07.063Z"
  },
  "monterosa": {
    "rating": "3.5",
    "description": "Monterosa Ski area has a rightful reputation for deep powder, huge off-piste frerride and great adventures. Monterosa Ski in Italy is set across three valleys south of the ever-present Monte Rosa massif - the heavily glaciated second highest peak in western Europe.\n\nWe rate Monterosa highly in both best overall & best powder ski resorts in Italy & Europe. It has been previously rated #1 in Italy for best overall ski resort & best for powder hounds. The mix of great snow, terrain, relatively low cost & lack of people (read - freshies all day) create a PPEPP - Perfect Place for European Powder Pleasure!",
    "pros": [
      "Highly rated over many seasons (Top 1 or 2 Best Overall & Best for Powderhounds 2018 to 2020)",
      "Mammoth skiable vertical of over 2,000m",
      "Reliable upper alpine snowpack.",
      "Uncrowded.",
      "Good value lift ticket price.",
      "Superb, unfettered off-piste terrain including tree skiing.",
      "Excellent length & variety of intermediate piste trails.",
      "Fresh tracks available days after last snowfall.",
      "Huge freeride and backcountry terrain to explore."
    ],
    "cons": [
      "Aging lift infrastructure.",
      "Limited advanced on-piste trails.",
      "Despite the statistics, Monterosa is poor for novices & beginners.",
      "Compared to other ski resorts, not the easiest place to get to in Europe.",
      "Not much for beginner skiers at the three main interlinked areas (but there are smaller ones nearby).",
      "Spread across an awfully long distance without a major single base area."
    ],
    "proOrCon": [
      "Relatively quiet nightlife.",
      "Not a lot of high-end accommodation (although that is changing - CampZero).",
      "For the vast majority, the backcountry requires a guide."
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": "Nov–earl",
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": "20",
      "vertical": "1,220m - 3,275m (2,075m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/Monterosa.aspx",
    "scrapedAt": "2026-02-18T06:21:16.291Z"
  },
  "pila": {
    "rating": "3.5",
    "description": "Pila ski resort in the Valle d'Aosta Italy is a most underrated skiing area. Pila has superb gondola access from the wonderful city of Aosta, ski-in ski-out accommodation plus fabulous snow and terrain.\n\nPila Provided a Powderhounds Plentiful Powder Paradise! That's the 6P tick of approval. The completion of the current 'Pila-Couis project' (which includes two new gondolas replacing several old chairlifts) will see a much-needed renewal of ski lifts & infrastructure at the resort, bringing it into line with other world-class ski areas.",
    "pros": [
      "Gondola access direct from the city of Aosta.",
      "North-facing terrain with excellent snow quality.",
      "Particularly good variety of piste trails for all levels, particularly intermediates.",
      "Excellent value lift ticket price (particularly on weekdays).",
      "Some challenging freeride terrain.",
      "Noticeably quiet during the week.",
      "Superb restaurants, food, drink and après ski."
    ],
    "cons": [
      "Very busy on weekends and holidays.",
      "Some old, slow lift infrastructure (that is being currently replaced - yay).",
      "Piste choke-point near village is dangerous.",
      "Some facilities are dated and a touch run down (rustica!)(but much of which is being renewed under the Pila-Couis project scheduled for completion by winter 25/26)."
    ],
    "proOrCon": [
      "Close to the major city of Aosta (but most people go elsewhere in the valley)!",
      "The slow lifts on the advanced terrain (rest, recover, crowd control or just too limiting?)"
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": "7km",
      "season": "Nov–mid",
      "beginner": "14%",
      "intermediate": "74%",
      "advanced": "12%",
      "lifts": "14",
      "vertical": "1,540m - 2,740m (1,200m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Italy/Pila.aspx",
    "scrapedAt": "2026-02-18T06:21:25.567Z"
  },
  "zermatt": {
    "rating": "4",
    "description": "Zermatt ski resort in Switzerland is considered by many to be one of the best resorts in Europe, if not the world. With the amazing Matterhorn looming high over town, Zermatt is certainly one of the most recognisable & fits the bill for many of the aspects that skiers & snowboarders are looking for on a quintessential European ski holiday.\n\nIt feels like you can ski forever at Zermatt. Vast terrain amongst spectacular surrounds and cruising intermediate runs that seem to never end. For those without superhuman fitness, thankfully many of slopes are intersected with fabulous mountain restaurants where you can have a lavish long lunch!\n\nThe views across many of the European ski resorts are fantastic, but Zermatt ski resort is in a class of its own. The resort sits at the foot of the iconic Matterhorn (4,478m) and on the flanks of the heavily glaciated Monte Rosa (4,634m). To say the scenery is incredible is understating it. Whilst it’s more of a town now than a village, Zermatt Switzerland has maintained some of its traditional European charm with a preserved 'old town', car free all year round & with the occasional horse drawn carriage travelling down the cobblestone streets. Last but not least, Zermatt resort both oozes panache & is delightfully luxurious for those looking to glam up their ski holidays; or can still provide a fabulous ski holiday experience for those on a budget.",
    "pros": [
      "Massive skiable vertical of over 2,200m & diverse ski terrain interlinked with Cervinia in Italy.",
      "Paradise for intermediate skiers & snowboarders and those who like to cruise.",
      "Superb off-piste freeride terrain & high-alpine backcountry ski touring.",
      "Combination of high altitude, northerly aspect & glaciers guarantee quality snow conditions.",
      "Skiing is available every day of the year.",
      "Fabulous, modern & efficient lift system proportionate to the lift pass price & monstrous terrain.",
      "Highest lifted point in Western Europe.",
      "Mountain scenery is beyond amazing.",
      "One of Europe’s best après ski runs (in the Furi sector).",
      "Sensational on-mountain accommodation away from the village.",
      "Plenty of off-slope activities for those who don’t ski or snowboard.",
      "On-mountain restaurants are some of the best in the world.",
      "By Swiss standards, the nightlife is vibrant plus there are options for those that want to party hard & those that just want to sedately sip a cocktail.",
      "Access to Zermatt is beautiful & easy via the train."
    ],
    "cons": [
      "Can be expensive (lift tickets are Europe's most expensive but still half the price of a lift pass in Vail USA plus accommodation & food can be just as confronting from a fiscal point of view).",
      "Limited valley-based ski-in ski-out accommodation.",
      "Lift queues develop during peak periods at some locations (to be expected in one of Europe's best-known ski resorts).",
      "Some off-piste terrain gets skied out very quickly on powder days (the easy to access bits anyway!).",
      "Localised high winds across the upper glacier terrain can often force lifts in that section to regularly close, including the link to Cervinia, Italy.",
      "Terrain is not well-suited to first time skiers; novice areas are limited (compared to the size of the resort) & there is no valley trail suitable for beginners (downloading required)."
    ],
    "proOrCon": [
      "Zermatt is popular with families (numerous ski schools & child-care options), but there aren’t many nursery slopes, particularly in poor weather.",
      "Ikon Pass is valid in the resort. (See the Lifts & Terrain page for more details).",
      "Village is ‘private car free’ meaning one cannot drive into Zermatt, you will just get run over by a silent, electric taxi instead!",
      "Due to the sprawling nature of the town & the lack of lower village ski-in ski-out accommodation, it can be a long walk/journey to ski school drop off/pick-up points, which may not be too much fun with small children attempting to carry their skis. Free local ski buses fulfill a few important routes, or a taxi may be required."
    ],
    "terrainStats": {
      "runs": "360km",
      "longestRun": "20km",
      "season": "Nov–May",
      "beginner": "22%",
      "intermediate": "60%",
      "advanced": "18%",
      "lifts": "61",
      "vertical": "Zermatt only 1,620m - 3,899m (2,279m) Incl. Cervinia & Valtournenche 1,524m - 3,899m (2,375m)",
      "snowfall": "10m+"
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Switzerland/Zermatt.aspx",
    "scrapedAt": "2026-02-18T06:21:36.716Z"
  },
  "st-moritz": {
    "rating": "4",
    "description": "Whilst for years it has simply traded on its name, St Moritz is rightfully a world renown ski resort. Comprising 3 diverse ski areas in the Upper Engadin of canton Grisons (or Graubünden), St Moritz Switzerland has terrain and activities for all skier abilities and non-skier proclivities!\n\nFeted as a playground for the wealthy, the St Moritz ski areas of Corviglia, Corvatsch & Diavolezza-Lagalb should instead be feted for the excellence of their lifts, pistes & freeride adventure possibilities.\n\nSt Moritz might be a little more expensive than some snow destinations in Switzerland & Europe, but it provides a superb ski experience for those with an open mind & a sense of adventure. The Powderhounds loved it.",
    "pros": [
      "Comprises three diverse ski areas.",
      "High altitude base - excellent snow quality.",
      "Modern and efficient lift infrastructure.",
      "Ski terrain for all levels of skier and snowboarder.",
      "Perfect sunny piste trails at Corviglia.",
      "Diverse terrain, glacier & north facing aspect on Corvatsch.",
      "Stunning freeride terrain at Diavolezza & Lagalb.",
      "Breathtaking rail journey from Zurich or Zermatt.",
      "Bernina Express train to Tirano Italy is one of the world's best rail journeys.",
      "Powder stays fresh and unsullied for days at St Moritz.",
      "Superb restaurants & fine dining (incl. on mountain).",
      "Over 230km of cross-country ski & winter walking trails.",
      "Massive range of non-ski activities & options."
    ],
    "cons": [
      "Expensive - particularly food & accommodation.",
      "Surprisingly quiet après ski in St Moritz town centre.",
      "St Moritz town centre has lost much of its traditional charm."
    ],
    "proOrCon": [
      "Three major ski areas that are not lift connected to each other.",
      "Not the simplest place to drive too (so take the train!).",
      "Can get seriously cold at St Moritz (great snow quality though!).",
      "High number of 5-star hotels!"
    ],
    "terrainStats": {
      "runs": null,
      "longestRun": "10km",
      "season": "Nov–earl",
      "beginner": "18%",
      "intermediate": "62%",
      "advanced": "20%",
      "lifts": "42",
      "vertical": "Corviglia 1,720m - 3,057m (1,337m) Corvatsch 1,797m - 3,303m (1,506m) Diavolezza 1,896m - 3,006m (1,110m)",
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Europe/Switzerland/St-Moritz.aspx",
    "scrapedAt": "2026-02-18T06:22:49.094Z"
  },
  "sierra-at-tahoe": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/California/Sierra-at-Tahoe.aspx",
    "scrapedAt": "2026-02-18T06:23:05.228Z"
  },
  "mammoth-mountain": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/California/Mammoth-Mountain.aspx",
    "scrapedAt": "2026-02-18T06:23:14.021Z"
  },
  "june-mountain": {
    "rating": "3",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/California/June-Mountain.aspx",
    "scrapedAt": "2026-02-18T06:23:25.858Z"
  },
  "alyeska": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Alaska/Alyeska.aspx",
    "scrapedAt": "2026-02-18T06:23:48.813Z"
  },
  "crystal-mountain": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Washington/Crystal-Mountain.aspx",
    "scrapedAt": "2026-02-18T06:25:02.980Z"
  },
  "mt-bachelor": {
    "rating": "3",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Oregon/Mt-Bachelor.aspx",
    "scrapedAt": "2026-02-18T06:25:56.749Z"
  },
  "schweitzer": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Idaho/Schweitzer.aspx",
    "scrapedAt": "2026-02-18T06:26:08.771Z"
  },
  "aspen-mountain": {
    "rating": "4.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Colorado/Aspen.aspx",
    "scrapedAt": "2026-02-18T06:26:21.582Z"
  },
  "aspen-highlands": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Colorado/Aspen-Highlands.aspx",
    "scrapedAt": "2026-02-18T06:26:32.249Z"
  },
  "buttermilk": {
    "rating": "3",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Colorado/Buttermilk.aspx",
    "scrapedAt": "2026-02-18T06:27:16.848Z"
  },
  "snowmass": {
    "rating": "4",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Colorado/Snowmass.aspx",
    "scrapedAt": "2026-02-18T06:27:27.656Z"
  },
  "steamboat": {
    "rating": "4",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Colorado/Steamboat.aspx",
    "scrapedAt": "2026-02-18T06:27:38.649Z"
  },
  "copper-mountain": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Colorado/Copper-Mountain.aspx",
    "scrapedAt": "2026-02-18T06:27:54.312Z"
  },
  "jackson-hole": {
    "rating": "3",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Wyoming/JacksonHole.aspx",
    "scrapedAt": "2026-02-18T06:29:58.114Z"
  },
  "big-sky": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Montana/BigSky.aspx",
    "scrapedAt": "2026-02-18T06:30:11.598Z"
  },
  "solitude": {
    "rating": "4",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Utah/Solitude.aspx",
    "scrapedAt": "2026-02-18T06:31:10.670Z"
  },
  "brighton": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Utah/Brighton.aspx",
    "scrapedAt": "2026-02-18T06:31:20.295Z"
  },
  "alta": {
    "rating": "4",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Utah/Alta.aspx",
    "scrapedAt": "2026-02-18T06:31:32.453Z"
  },
  "snowbird": {
    "rating": "4",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Utah/Snowbird.aspx",
    "scrapedAt": "2026-02-18T06:31:40.081Z"
  },
  "snowbasin": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Utah/Snowbasin.aspx",
    "scrapedAt": "2026-02-18T06:31:49.988Z"
  },
  "stratton": {
    "rating": "0",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Vermont/Stratton.aspx",
    "scrapedAt": "2026-02-18T06:32:03.062Z"
  },
  "sugarbush": {
    "rating": "0",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/USA/Vermont/Sugarbush.aspx",
    "scrapedAt": "2026-02-18T06:32:14.594Z"
  },
  "valle-nevado": {
    "rating": "3",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/SouthAmerica/Chile/Valle-Nevado.aspx",
    "scrapedAt": "2026-02-18T06:34:15.132Z"
  },
  "thredbo": {
    "rating": "3",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Other/Australia/Thredbo.aspx",
    "scrapedAt": "2026-02-18T06:34:24.786Z"
  },
  "mt-buller": {
    "rating": "2.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Other/Australia/Mt-Buller.aspx",
    "scrapedAt": "2026-02-18T06:34:34.848Z"
  },
  "remarkables": {
    "rating": "3",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/NewZealand/Remarkables.aspx",
    "scrapedAt": "2026-02-18T06:34:54.094Z"
  },
  "niseko": {
    "rating": "4",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Japan/Hokkaido/Niseko.aspx",
    "scrapedAt": "2026-02-18T06:36:58.265Z"
  },
  "arai": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Japan/Honshu/Arai.aspx",
    "scrapedAt": "2026-02-18T06:37:08.177Z"
  },
  "shiga-kogen": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Japan/Honshu/Shiga-Kogen.aspx",
    "scrapedAt": "2026-02-18T06:37:20.277Z"
  },
  "furano": {
    "rating": "4",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Japan/Hokkaido/Furano.aspx",
    "scrapedAt": "2026-02-18T06:37:39.579Z"
  },
  "zao": {
    "rating": "3.5",
    "description": "",
    "pros": [],
    "cons": [],
    "proOrCon": [],
    "terrainStats": {
      "runs": null,
      "longestRun": null,
      "season": null,
      "beginner": null,
      "intermediate": null,
      "advanced": null,
      "lifts": null,
      "vertical": null,
      "snowfall": null
    },
    "sourceUrl": "https://www.powderhounds.com/Japan/Honshu/Zao-Onsen.aspx",
    "scrapedAt": "2026-02-18T06:37:53.415Z"
  }
};
